version: '3.1'

services:
  be:
    build:
      context: ./humako
    ports:
    - 3010:3010
  db:
    build:
      context: ./postgres
    ports:
     - 5432:5432
  fe:
    build:
      context: ./frontend
    volumes:
     - /docker-volumes/etc/letsencrypt/live/humako.voorkanter.com/fullchain.pem:/etc/letsencrypt/live/humako.voorkanter.com/fullchain.pem
     - /docker-volumes/etc/letsencrypt/live/humako.voorkanter.com/privkey.pem:/etc/letsencrypt/live/humako.voorkanter.com/privkey.pem
    ports:
     - 443:443       
     - 80:80
