[package]
name = "worksheets"
version = "0.1.0"
authors = ["Michel van der Hulst <michel@voorkanter.com>"]
edition = "2018"

[dependencies]
events = { path = "../events" }
db-parser = { path = "../db-parser" }
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0"